[opener]
play = [
	{ run = 'vlc "$@"', desc = "vlc", orphan = true, for = "unix" }
]
img = [
	{ run = 'feh "$@"', desc = "feh", orphan = true, for = "unix" }
]

[open]
rules = [
	{ mime = "image/*", use = "img" },
]
